services:
  cardioversor:
      container_name: ${APP_NAME:-cardioversor}-${ENV_NAME:-dev}
      image: ${APP_NAME:-cardioversor}:${ENV_NAME:-dev}
      build:
        context: ./cardioversor
        dockerfile: ./Dockerfile
        args:
          APP_NAME: ${APP_NAME:-cardioversor}
          ENV_NAME: ${ENV_NAME:-dev}
      ports:
        - "${SINAIS_VITAIS_PORT:-7004}:8000"
      volumes:
        - ./cardioversor:/usr/app
      restart: unless-stopped
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:${BACKEND_PORT:-7004}/health || exit 1"]
        interval: 1m
        timeout: 10s
        retries: 5