services:
  cardioversor:
      container_name: ${APP_NAME:-cardioversor}-${ENV_NAME:-dev}
      image: ${APP_NAME:-cardioversor}:${ENV_NAME:-dev}
      build:
        context: .
        dockerfile: ./cardioversor/Dockerfile
        args:
          APP_NAME: ${APP_NAME:-cardioversor}
          ENV_NAME: ${ENV_NAME:-dev}
      ports:
        - "${SINAIS_VITAIS_PORT:-7004}:8000"
      restart: unless-stopped
      env_file:
        - .env
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:${BACKEND_PORT:-7004}/health || exit 1"]
        interval: 1m
        timeout: 10s
        retries: 5
      networks:
        - uti-monitor-sinais-vitais_projeto_uti

networks:
  uti-monitor-sinais-vitais_projeto_uti:
    external: true